import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TanstackProvider } from "@/providers/TanstackProvider";
import { Toaster } from "@/components/ui/sonner";
import { DynamicLayout } from "@/components/dynamic-layout";
import { SocketProvider } from "@/providers/SocketProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SocketProvider>
          <TanstackProvider>
            <Toaster />
            <DynamicLayout navCollapsedSize={0}>{children}</DynamicLayout>
          </TanstackProvider>
        </SocketProvider>
      </body>
    </html>
  );
}
